#!/bin/bash

if [[ $EUID -ne 0 ]]; then
	echo "You need root to update your themes!"
	exit 1
fi

themes=(/boot/grub/themes/*/)
themes=("${themes[@]%/}")
themes=("${themes[@]##*/}")

echo "These are the available themes:"
for (( i = 0; i < ${#themes[@]}; i++)); do
	echo "$((i+1))) ${themes[i]}"
done
read -p "Select a theme to install: " selected_theme
selected_theme=$(($selected_theme - 1))

while [[ $selected_theme -gt $((${#themes[@]}-1)) ]] || [[ $selected_theme -lt 0 ]]; do
	read -p "Invalid theme number. Try again: " selected_theme
	selected_theme=$(($selected_theme - 1))
done

echo "You selected ${themes[$selected_theme]}"

sed -i "s|GRUB_THEME=.*|GRUB_THEME=\"/boot/grub/themes/${themes[$selected_theme]}/theme.txt\"\\n|" /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg
