#!/bin/bash

if [[ $EUID -ne 0 ]]; then
	echo "You need root to update your themes!"
	exit 1
fi

themes=(/boot/grub/themes/*/)
themes=("${themes[@]%/}")
themes=("${themes[@]##*/}")

installed_theme=$(grep GRUB_THEME=* /etc/default/grub)

echo "These are the available themes:"
for (( i = 0; i < ${#themes[@]}; i++)); do
	if [[ "$installed_theme" =~ "${themes[i]}" ]]; then
		echo "$((i+1))) ${themes[i]} [Installed]"
	else
		echo "$((i+1))) ${themes[i]}"
	fi
done
read -p "Select a theme to install: " selected_theme
selected_theme=$(($selected_theme - 1))

while [[ $selected_theme -gt $((${#themes[@]}-1)) ||  $selected_theme -lt 0 ]] || [[ "$installed_theme" =~ "${themes[$selected_theme]}" ]]; do
	if [[ "$installed_theme" =~ "${themes[$selected_theme]}" && -n "${themes[$selected_theme]}" ]]; then
		read -p "Theme is already installed! Try again: " selected_theme
	else
		read -p "Invalid theme number. Try again: " selected_theme
	fi
	selected_theme=$(($selected_theme - 1))
done

echo "You selected ${themes[$selected_theme]}"

sed -i "s|GRUB_THEME=.*|GRUB_THEME=\"/boot/grub/themes/${themes[$selected_theme]}/theme.txt\"\\n|" /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg